### ISSUE TITLE
api_key.dart is missing

### ISSUE THREAD

**Issue by shariful2011** [FrancaTM/ice-cream-stores-demo#1]
api_key.dart is missing. Can you please provide?

**Comment by FrancaTM** [comment]
hi @shariful2011, you need to generate your own api key for google maps in google cloud platform. After that you can create another file called "api_key.dart" and insert your generated key there.
Example:

const googleMapsApiKey = '[generated api key here]';

I hope this helps!

Ps: I'm sorry for the delay, I just saw your issue today! :/

**Comment by FrancaTM** [comment]
@shariful2011 I've updated the repo to simplify the project execution for others. Please, check the repo again! :)
