### ISSUE TITLE
Did you ever get this to work, I can't figure out how to make the lat and long work in the fire cloud database.

### ISSUE THREAD

**Issue by richtong** [FrancaTM/ice-cream-stores-demo#3]
That is, if you just type in the strings that you suggest, it obviously barfs. because it is expected that the lat and long are selectable. I'm guesisng, it actually wants Json more like [latitude: 32.4] etc.

I have a PR for you that explains what types the dtabase needs, looks like location is the second type.

**Comment by FrancaTM** [comment]
Hi @richtong and I'm sorry for the late reply.

The location in the sample data is just a simple geopoint (latitude and longitude structure) in firestore (just by the image in the readme that is hard to spot, I think).

If that was not your problem, I did some updates (5195307b50a4e18fa153ef5e05a360fbe6b190a7) on the project, basically removing some configuration files for android and iOS (I exposed my firebase project configuration and people could be trying to access my blocked database by default, shame on me :| ) that you need to put inside the project after creating the android and iOS apps in firebase (but I think that was not your case).

I didn't find any PR from you, are you sure you've created one? Thanks richtong and I'm sorry again for the delay in the response

**Comment by richtong** [comment]
No worries. I got it all working. Added a readme to get it all working. 

So ill submit it to u. Do u want?

Thanks,
Rich

—
“History never repeats itself, but the Kaleidoscopic combinations of the pictured present often seems to be constructed out of the broken fragments of antique legends.” The Gilded Age: A Tale of To-day, Mark Twain and Charles Dudley Warren, 1874. https://quoteinvestigator.com/2014/01/12/history-rhymes/

+1-206-963-9029 | https://tongfamily.com | @richtong | https://fb.me/richtong | https://linkedin.com/in/richtong1 | https://www.strava.com/athletes/21412713

Sent from my iPhone X
—

**Comment by FrancaTM** [comment]
Ok, great.

I don't think that will be necessary, thank you richtong!
